### ISSUE TITLE
BE, FE, MVPs 

### ISSUE THREAD

**Issue by cindyytong** [lifesscholar/Other-reads#3]
Hi Neev:

Nice work! Let's have a 1:1 kickoff meeting on Monday to align on everything and your first MVP.  

- [x] Please see slack message about having your app focused on movies instead of books. Not required but an idea to differentiate. 
- [x] If after studying for the assessment this weekend and you have an hour to put together simple wireframes, I highly recommend that for each FE route if you can take a screenshot of the live site and map the user flow to the FE and BE routes it will make the dev of this easier. See example: https://docs.google.com/presentation/d/1XwWw5dBz774zBUmvsu3IOcZAaJGbna1FYvAqtkQ57RQ/edit?usp=sharing
- [x] MVP item 3: Add bullet for setting up Google Books api to seed data 

**FE Routes**
- [x] `NavBar` component look into the variations you will need (i.e. logged in, logged out on splash page versus logged out on search results page) [example](https://www.goodreads.com/genres/art) 
- [ ] Include container components you will need for all routes
- [ ] Identify next to each route if they are auth (must be logged out) or protected (must be logged in) 
- [ ] `/` Identify the components that should be shown when the user is logged in. See sample below 
![Screen Shot 2020-02-08 at 3 32 50 PM](https://user-images.githubusercontent.com/13906893/74091709-5927a700-4a88-11ea-9b59-33c3815be7e4.png)
-[ ] For your MVP 3 where users can search across Books, add search across genres as well.  We should have in Schema a genres table and books should have foreign key pointing to genre. Also add FE route for `/genres` ([see live site ](https://www.goodreads.com/genres) )  which will give list of genres with links to `/genres/genreName` ([see live site ](https://www.goodreads.com/genres/manga) )
-[ ] add `/search` which is accessible logged in and logged out [example ](https://www.goodreads.com/search?q=art+history&qid=) . Pls note you have the search in the navBar and also the search with filters on the search results page
- [ ] For reviews we should also have 
* `reviews/reviewId` for `reviewDetail`
* `reviews/reviewId/edit` for `reviewForm` which can be shared for creating and updating a review

**Comment by lifesscholar** [comment]
I think I have finished all of these issues. One Point: I am not going to do an author's table and page for time constraints.
